# Generated by Django 4.1.6 on 2023-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(max_length=15, verbose_name='Год издания'),
        ),
    ]
